# Generated by Django 5.0.3 on 2024-04-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.PositiveIntegerField()),
                ('one_id', models.PositiveIntegerField()),
                ('two_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(max_length=123)),
                ('chat_id', models.PositiveIntegerField()),
                ('from_id', models.PositiveIntegerField()),
                ('to_id', models.PositiveIntegerField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('catalog_id', models.PositiveIntegerField()),
                ('order_type', models.CharField(max_length=123)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prepaid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency_id', models.PositiveIntegerField()),
                ('payment_type_id', models.PositiveIntegerField()),
                ('from_region_id', models.PositiveIntegerField()),
                ('to_region_id', models.PositiveIntegerField()),
                ('from_address', models.CharField(max_length=223)),
                ('to_address', models.CharField(max_length=223)),
                ('transport_type_id', models.PositiveIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('brutto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transport_document_id', models.PositiveIntegerField()),
                ('region_id', models.PositiveIntegerField()),
                ('status_id', models.PositiveIntegerField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('note', models.TextField()),
                ('status', models.CharField(max_length=123)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('order_item_type', models.CharField(max_length=123)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prepaid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency_id', models.PositiveIntegerField()),
                ('payment_type_id', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('brutto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status_id', models.PositiveIntegerField()),
                ('owner_id', models.PositiveIntegerField()),
                ('executor_id', models.PositiveIntegerField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('order_on', models.PositiveIntegerField()),
                ('change_allow_status', models.CharField(max_length=123)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('is_liked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.PositiveIntegerField()),
                ('to_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order_item_id', models.PositiveIntegerField()),
                ('payment_type_id', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=123)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.PositiveIntegerField()),
                ('to_id', models.PositiveIntegerField()),
                ('payment_id', models.PositiveIntegerField()),
                ('order_item_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('order_on', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
