# Generated by Django 5.0.3 on 2024-04-27 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_carbrand_car_type_id_and_more'),
        ('order', '0003_alter_chat_one_id_alter_chat_two_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='message_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderapplicant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderapplicant',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_applicant_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='one_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_one_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='order_item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_item', to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='two_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_two_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_region', to='main.region'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_id',
            field=models.ForeignKey(default='Active', on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='order.orderstatus'),
        ),
        migrations.AlterField(
            model_name='orderapplicant',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_applicant_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderapplicant',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('OwnerCancelled', 'OwnerCancelled'), ('InvitedCancelled', 'InvitedCancelled'), ('Accepted', 'Accepted')], default='New', max_length=123),
        ),
        migrations.AlterField(
            model_name='orderview',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_view', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderview',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_view_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='from_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_from_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_item_id', to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_payment_type_id', to='main.paymenttype'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Waiting', 'Waiting'), ('Approved', 'Approved')], default='Pending', max_length=123),
        ),
        migrations.AlterField(
            model_name='payment',
            name='to_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_to_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_transaction_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_transaction_id', to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction_id', to='order.payment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_transaction_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
