# Generated by Django 5.0.3 on 2024-06-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfiles',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_files', to='order.order'),
        ),
    ]
