# Generated by Django 5.0.3 on 2024-04-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_type',
            field=models.CharField(choices=[('Continent', 'Continent'), ('Country', 'Country'), ('District', 'District')], max_length=123),
        ),
    ]
