# Generated by Django 5.0.3 on 2024-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_region_region_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='type_catalog',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=123),
        ),
    ]
