# Generated by Django 5.0.3 on 2024-04-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_catalog_type_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio'), ('Image', 'Image')], default='Video', max_length=123),
        ),
    ]
