# Generated by Django 5.0.3 on 2024-04-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_region_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='car_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cartype'),
        ),
        migrations.AlterField(
            model_name='carmark',
            name='car_brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.carbrand'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='car_weight_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.carweighttype'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.catalog'),
        ),
    ]
