# Generated by Django 5.0.3 on 2024-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportinformation',
            name='passport_back',
            field=models.FileField(null=True, upload_to='passport/'),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='passport_with_face',
            field=models.FileField(null=True, upload_to='passport/'),
        ),
    ]
