# Generated by Django 5.0.3 on 2024-06-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_transportinformation_passport_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportinformation',
            name='car_gos_number',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='driver_license_back',
            field=models.FileField(null=True, upload_to='driver_license/'),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='driver_license_expiration',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='driver_license_seria_number',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='driver_license_with_face',
            field=models.FileField(null=True, upload_to='driver_license/'),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='passport_seria_number',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='tex_passport',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='tex_passport_back',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='trailer_gos_number',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='trailer_passport',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='trailer_passport_back',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
